version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
      - GCP_DATASTORE_URL=http://datastore:8080
      - GCP_PROJECT_ID=anlg
      - ADDRESS=0.0.0.0:8000
    volumes:
      - ./api/src:/app/src
    depends_on:
      - datastore
  datastore:
    build:
      context: ./datastore
      dockerfile: Dockerfile
    ports:
      - "8010:8080"
    environment:
      - PROJECT_ID=anlg
      - HOST_PORT=0.0.0.0:8080
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    environment:
      - SERVER_URL=http://localhost:8000
    volumes:
      - ./front:/app
