services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
      - RUST_LOG=info
      - GCP_PROJECT_ID=anlg-399912
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud/application_default_credentials.json
      - ADDRESS=0.0.0.0:8000
      #- ACCESS_TOKEN=ACCESS_TOKEN
      - OPENAI_API_KEY
    volumes:
      - ./api/src:/app/src
      - ./firestore/gcloud:/app/gcloud
    depends_on:
      - firestore
  firestore:
    build:
      context: .
      dockerfile: ./firestore/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./firestore/gcloud:/root/.config/gcloud
  # front:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:5173"
  #   environment:
  #     - VITE_API_URL=http://localhost:8000
  #   volumes:
  #     - ./front:/app
