version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api/src:/app/src
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:5173
    environment:
      - SERVER_URL
    volumes:
      - ./front:/app
