[package]
name = "anlg-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "6.0.6"
async-graphql-actix-web = "6.0.6"
actix-web = { version = "4.1.0", default-features = false, features = ["http2", "macros"] }
