FROM rust:1.72 as chef
WORKDIR /app

RUN cargo install cargo-chef cargo-watch

FROM chef as planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef as runtime
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

COPY . .

CMD ["cargo", "watch", "-x", "run"]
